---
- name: Welcome to LaluBuntu! ^.^
  hosts: localhost
  connection: local
  roles:
    - role: roles/base-install
    - role: roles/offensive-stuff
    - role: roles/gui-tools
    - role: roles/hardening
      users:
        - username: "{{ ansible_user_id }}"
