---
- name: Check if NoMachine is already installed
  ansible.builtin.stat:
    path: '/usr/bin/nomachine'
  register: nomachine_installed
  become: true

- name: Get NoMachine URL
  ansible.builtin.uri:
    url: '{{ nomachine_download_url }}'
    return_content: yes
  register: nomachine_page
  when: not nomachine_installed.stat.exists

- name: Extract NoMachine URL
  ansible.builtin.set_fact:
    nomachine_url: "{{ nomachine_page.content | regex_findall('https:\/\/download.nomachine.com\/download\/[0-9].[0-9][0-9]\/Linux\/nomachine_[0-9].[0-9][0-9].[0-9]_[0-9]_amd64.deb') | unique | first }}"
  when: 
   - nomachine_url is not defined
   - not nomachine_installed.stat.exists

- name: Download nomachine
  ansible.builtin.get_url:
    url: '{{ nomachine_url }}'
    dest: '/tmp/nomachine-setup.deb'
  when: not nomachine_installed.stat.exists

- name: Install nomachine
  ansible.builtin.apt:
    deb: '/tmp/nomachine-setup.deb'
    state: present
  become: true
  when: not nomachine_installed.stat.exists

- name: Delete file /tmp/nomachine-setup.deb
  ansible.builtin.file:
    path: '/tmp/nomachine-setup.deb'
    state: absent
  when: not nomachine_installed.stat.exists