- name: Check if cameractrls is already installed
  ansible.builtin.stat:
    path: '{{ ansible_env.HOME }}/.local/share/applications/hu.irl.cameractrls.desktop.noexist' # Force reinstall to fix previous broken path, rm .noexist in early April 2024
  register: cameractrls_installed

- name: Install CameraCtrls
  when: not cameractrls_installed.stat.exists
  block:
    - name: Install required packages for cameractrls
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
      become: true
      with_items:
        - libsdl2-2.0-0
        - libturbojpeg

    - name: Clone cameractrls repository
      ansible.builtin.git:
        repo: 'https://github.com/soyersoyer/cameractrls.git'
        dest: /opt/cameractrls
        force: yes
      become: true

    - name: Change ownership of the directory
      ansible.builtin.file:
        path: '/opt/cameractrls'
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        recurse: yes
      become: true

    - name: Run cameractrls installer
      ansible.builtin.command:
        cmd: 'desktop-file-install --dir="{{ ansible_env.HOME }}/.local/share/applications" --set-key=Exec --set-value="/opt/cameractrls/cameractrlsgtk4.py" --set-key=Path --set-value="/opt/cameractrls" --set-key=Icon --set-value="/opt/cameractrls/pkg/hu.irl.cameractrls.svg" pkg/hu.irl.cameractrls.desktop'
        chdir: /opt/cameractrls
