---
- name: Check if NoMachine is already installed
  ansible.builtin.stat:
    path: '/usr/NX/bin/nxserver.bin'
  register: nomachine_installed

- name: Install NoMachine if not already installed
  ignore_errors: true
  when: not nomachine_installed.stat.exists
  block:
    - name: Download nomachine
      ansible.builtin.get_url:
        url: 'https://download.nomachine.com/download/8.14/Linux/nomachine_8.14.2_1_amd64.deb'
        dest: '/tmp/nomachine-setup.deb'

    - name: Install nomachine
      ansible.builtin.apt:
        deb: '/tmp/nomachine-setup.deb'
        state: present
      become: true

    - name: Delete file /tmp/nomachine-setup.deb
      ansible.builtin.file:
        path: '/tmp/nomachine-setup.deb'
        state: absent

- name: Stop and disable Nomachine
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: no
    state: stopped
  loop_control:
    loop_var: item
  become: true
  ignore_errors: true
  with_items:
    - nxserver
