---
- name: Check if VsCode is already installed
  ansible.builtin.stat:
    path: '/usr/bin/code'
  register: vscode_installed

- name: Download VsCode
  ansible.builtin.get_url:
    url: 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64'
    dest: '/tmp/vscode-setup.deb'
    http_agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/83.0.4103.106 Chrome/83.0.4103.106 Safari/537.36'
  when: not vscode_installed.stat.exists

- name: Install VsCode
  ansible.builtin.apt:
    deb: '/tmp/vscode-setup.deb'
    state: present
  become: true
  when: not vscode_installed.stat.exists

- name: Delete file /tmp/vscode-setup.deb
  ansible.builtin.file:
    path: '/tmp/vscode-setup.deb'
    state: absent
  when: not vscode_installed.stat.exists

- name: Set GNOME Preferences
  ansible.builtin.shell: code --install-extension '{{ item }}'
  with_items:
    - bibhasdn.unique-lines
    - eriklynd.json-tools
    - github.copilot
    - github.copilot-chat
    - mechatroner.rainbow-csv
    - mitchdenny.ecdc
    - ms-azuretools.vscode-docker
    - ms-python.debugpy
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode.remote-explorer
    - ms-vsliveshare.vsliveshare
    - trailofbits.weaudit
    - usernamehw.errorlens
    - yzane.markdown-pdf
    - zobo.php-intellisense
