---
- name: Check if Veracrypt is already installed
  ansible.builtin.stat:
    path: '/usr/bin/veracrypt'
  register: veracrypt_installed
  become: true

- name: Get Veracrypt URL
  ansible.builtin.uri:
    url: '{{ veracrypt_download_url }}'
    return_content: true
  register: veracrypt_release
  when: not veracrypt_installed.stat.exists

- name: Set the filename and download url
  set_fact:
    filename: '{{ asset_file.name }}'
    download_url: '{{ asset_file.browser_download_url }}'
  vars:
    asset_file: "{{ veracrypt_release.json.assets | selectattr('name', 'match', '.*Ubuntu-22.04-amd64.deb(?!\\.sig).*') | rejectattr('name', 'search', 'veracrypt-console') | join() }}"
  when: not veracrypt_installed.stat.exists

- name: Download Veracrypt
  ansible.builtin.get_url:
    url: '{{ download_url }}'
    dest: '/tmp/veracrypt-setup.deb'
  when: not veracrypt_installed.stat.exists

- name: Install Veracrypt
  ansible.builtin.apt:
    deb: '/tmp/veracrypt-setup.deb'
    state: present
  become: true
  when: not veracrypt_installed.stat.exists

- name: Delete file /tmp/veracrypt-setup.deb
  ansible.builtin.file:
    path: '/tmp/veracrypt-setup.deb'
    state: absent
  when: not veracrypt_installed.stat.exists