---
- name: Check if Signal is already installed
  ansible.builtin.stat:
    path: /usr/bin/signal-desktop
  register: signal_installed

- name: Add signal key
  ansible.builtin.shell: "wget -qO- {{ signal_key_url }} | gpg --dearmor > /usr/share/keyrings/signal-desktop-keyring.gpg"
  become: true
  when: not signal_installed.stat.exists

- name: Add Signal repository line to sources.list.d
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/signal-xenial.list
    line: '{{ signal_repo_url }}'
    create: yes
  become: true
  when: not signal_installed.stat.exists

- name: Install Signal
  ansible.builtin.package:
    update_cache: yes
    name:
      - signal-desktop
    state: latest
  become: true
  when: not signal_installed.stat.exists