---
- name: Install VsCode only if /usr/bin/code does not exist
  ansible.builtin.stat:
    path: /usr/bin/code
  register: file_check

- name: Install VsCode following their doc
  shell: |
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
    sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
    rm -f packages.microsoft.gpg
    apt-get update
    apt-get install -y code
  become: true
  when: not file_check.stat.exists
