---
- name: Check if Veracrypt is already installed
  ansible.builtin.stat:
    path: '/usr/bin/veracrypt'
  register: veracrypt_installed
  become: true

- name: Download Veracrypt
  ansible.builtin.get_url:
    url: 'https://github.com/veracrypt/VeraCrypt/releases/download/VeraCrypt_1.26.14/veracrypt-1.26.14-Ubuntu-24.04-amd64.deb'
    dest: '/tmp/veracrypt-setup.deb'
  when: not veracrypt_installed.stat.exists

- name: Install Veracrypt
  ansible.builtin.apt:
    deb: '/tmp/veracrypt-setup.deb'
    state: present
  become: true
  when: not veracrypt_installed.stat.exists

- name: Delete file /tmp/veracrypt-setup.deb
  ansible.builtin.file:
    path: '/tmp/veracrypt-setup.deb'
    state: absent
  when: not veracrypt_installed.stat.exists