---
- name: Check if Veracrypt is already installed
  ansible.builtin.stat:
    path: /usr/bin/veracrypt
  register: veracrypt_installed
  become: true

- name: Get Veracrypt URL
  ansible.builtin.uri:
    url: '{{ veracrypt_download_url }}'
    return_content: yes
  register: veracrypt_page
  when: not veracrypt_installed.stat.exists

- name: Extract Veracrypt URL
  ansible.builtin.set_fact:
    vera_url: "{{ veracrypt_page.content | regex_findall('https://.*?veracrypt-[0-9]+\\.[0-9]+\\.[0-9]+-Ubuntu-22\\.04-amd64\\.deb') | unique | first |  regex_replace('&#43;', '+')}}"
  when: 
   - vera_url is not defined
   - not veracrypt_installed.stat.exists

- name: Download Veracrypt
  ansible.builtin.get_url:
    url: "{{ vera_url }}"
    dest: /tmp/veracrypt-setup.deb
  when: not veracrypt_installed.stat.exists

- name: Install Veracrypt
  ansible.builtin.apt:
    deb: /tmp/veracrypt-setup.deb
    state: present
  become: true
  when: not veracrypt_installed.stat.exists

- name: Delete file /tmp/veracrypt-setup.deb
  ansible.builtin.file:
    path: /tmp/veracrypt-setup.deb
    state: absent
  when: not veracrypt_installed.stat.exists