---
- name: Install Regolith Certificates only if /etc/apt/sources.list.d/regolith.list does not exist
  ansible.builtin.stat:
    path: '/etc/apt/sources.list.d/regolith.list'
  register: regolith_installed

- name: Download Regolith key
  ansible.builtin.get_url:
    url : '{{ regolith_key_url }}'
    dest: '/tmp/rego_gpg'
  when: not regolith_installed.stat.exists

- name: De-Armor Regolith GPG key
  ansible.builtin.shell: 'gpg --dearmor < /tmp/rego_gpg > {{ regolith_gpg_dest }} && rm /tmp/rego_gpg'
  become: true
  when: not regolith_installed.stat.exists

- name: Add Regolith repository
  ansible.builtin.lineinfile:
    path: '/etc/apt/sources.list.d/regolith.list'
    line: '{{ regolith_repo_url }}'
    create: yes
  become: true
  when: not regolith_installed.stat.exists

- name: Set lightdm as the default X display manager
  ansible.builtin.debconf:
    name: lightdm
    question: 'shared/default-x-display-manager'
    value: 'lightdm'
    vtype: 'select'
  become: true
  when: not regolith_installed.stat.exists

- name: Update APT package cache and install Regolith Desktop
  ansible.builtin.package:
    update_cache: yes
    name: '{{ item }}'
    state: latest
  environment:
    DEBIAN_FRONTEND: noninteractive
  loop: '{{ regolith_packages }}'
  become: true
  when: not regolith_installed.stat.exists

- name: Install i3 packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  loop: '{{ i3_packages }}'
  become: true
  when: not regolith_installed.stat.exists


- name: Ensure the ~/.config/regolith3/i3/config.d/ directory exists
  ansible.builtin.file:
    path: '{{ ansible_user_id }}/.config/regolith3/i3/config.d/'
    state: directory

- name: Append lines to the i3 config file
  ansible.builtin.blockinfile:
    path: '{{ ansible_user_id }}/.config/regolith3/i3/config.d/config'
    block: '{{ i3_config_block }}'
    create: yes

- name: Append lines to the i3 Xresources file
  ansible.builtin.blockinfile:
    path: '{{ ansible_user_id }}/.config/regolith3/Xresources'
    block: '{{ i3_xresources_block }}'
    create: yes

- name: Set GNOME interface to prefer dark color scheme
  ansible.builtin.shell: "gsettings set org.gnome.desktop.interface color-scheme prefer-dark"

- name: Set click on touchpad enable
  ansible.builtin.shell: "gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true"