---
- name: Install Regolith Certificates only if /etc/apt/sources.list.d/regolith.list does not exist
  ansible.builtin.stat:
    path: '/etc/apt/sources.list.d/regolith.list'
  register: regolith_installed

- name: Download Regolith key
  ansible.builtin.get_url:
    url : 'https://regolith-desktop.org/regolith.key'
    dest: '/tmp/rego_gpg'
  when: not regolith_installed.stat.exists

- name: De-Armor Regolith GPG key
  ansible.builtin.shell: 'gpg --dearmor < /tmp/rego_gpg > /usr/share/keyrings/regolith-archive-keyring.gpg && rm /tmp/rego_gpg'
  become: true
  when: not regolith_installed.stat.exists

- name: Add Regolith repository
  ansible.builtin.lineinfile:
    path: '/etc/apt/sources.list.d/regolith.list'
    line: 'deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/release-3_2-ubuntu-noble-amd64 noble main'
    create: yes
    state: present
  become: true
  when: not regolith_installed.stat.exists

- name: Update APT package cache and install Regolith Desktop
  ansible.builtin.package:
    update_cache: yes
    name: '{{ item }}'
    state: latest
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: true
  with_items:
    - regolith-desktop
    - regolith-look-nord
    - regolith-session-flashback

- name: Install i3 packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  become: true
  with_items:
    - i3xrocks-battery
    - i3xrocks-bluetooth
    - i3xrocks-cpu-usage
    - i3xrocks-disk-capacity
    - i3xrocks-focused-window-name
    - i3xrocks-info
    - i3xrocks-memory
    - i3xrocks-microphone
    - i3xrocks-net-traffic
    - i3xrocks-temp
    - i3xrocks-time
    - i3xrocks-updates
    - i3xrocks-volume
    - i3xrocks-wifi
    # - i3xrocks-rofication
    # - i3xrocks-app-launcher
    # - i3xrocks-key-indicator
    # - i3xrocks-keyboard-layout
    # - i3xrocks-media-player
    # - i3xrocks-next-workspace
    # - i3xrocks-nm-vpn
    # - i3xrocks-openvpn
    # - i3xrocks-tailscale
    # - i3xrocks-weather

- name: Remove Picom as it breads NoMachine screen refresh
  ansible.builtin.package:
    name: picom
    state: absent
  become: true
  when: not regolith_installed.stat.exists

- name: Replace regolith-rofication (auto removed) by dunst
  ansible.builtin.package:
    update_cache: yes
    name: dunst
    state: latest
  become: true

- name: Kill Picom after it's removed
  become: true
  ansible.builtin.shell: pkill picom
  ignore_errors: true

- name: Ensure the ~/.config/regolith3/i3/config.d/ directory exists
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config/regolith3/i3/config.d/'
    state: directory

- name: Append lines to the i3 config file
  ansible.builtin.blockinfile:
    path: '{{ ansible_env.HOME }}/.config/regolith3/i3/config.d/config'
    create: yes
    block: |
      bindsym $mod+p exec flameshot gui
      bindsym $mod+Ctrl+p exec flameshot full -p /tmp/
      bindsym $mod+s exec gnome-control-center sound
      bindsym $mod+e exec emote
      bindsym $mod+Shift+w exec /usr/bin/python3 /opt/cameractrls/cameractrlsgtk4.py
      bindsym $mod+m exec pactl set-source-mute @DEFAULT_SOURCE@ toggle && notify-send --icon=/dev/null --expire-time=500 "$(pactl get-source-mute @DEFAULT_SOURCE@)"

- name: Set GNOME Preferences
  ansible.builtin.shell: |
    regolith-look set nord
    echo "regolith.wallpaper.file: /opt/lalubuntu/screens/wallpaper.png" >> "{{ ansible_env.HOME }}/.config/regolith3/Xresources"
    gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true # enable tap-to-click
    gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'fr')]"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    gsettings set org.gnome.desktop.interface document-font-name 'Sans 12'
    gsettings set org.gnome.desktop.interface font-antialiasing 'grayscale'
    gsettings set org.gnome.desktop.interface font-hinting 'slight'
    gsettings set org.gnome.desktop.interface font-name 'Nerd Font Mono 10'
    gsettings set org.gnome.desktop.interface font-rgba-order 'rgb'

- name: Use the right terminal emulator
  ansible.builtin.shell: update-alternatives --set x-terminal-emulator /usr/bin/gnome-terminal.wrapper
  become: true
