---
# defaults file for gui-tools
gui_tools_to_install:
  - apt-transport-https
  - arandr
  # - bless
  - blueman
  - cheese
  - filezilla
  - flameshot
  - gnome-tweaks
  - gparted
  - kompare
  - libgtk-3-dev
  - libreoffice
  - mplayer
  - pavucontrol
  - qbittorrent
  - qemu
  - torbrowser-launcher
  - usb-creator-gtk
  - vlc
  - wireshark
  - dunst
  - okular

chrome_gpg_dest: '/etc/apt/trusted.gpg.d/chrome.gpg'
chrome_deb_url: 'deb [arch=amd64 signed-by={{ chrome_gpg_dest }}] https://dl.google.com/linux/chrome/deb/ stable main'
chrome_gpg_key_id: '78BD65473CB3BD13'
chrome_key_server: 'keyserver.ubuntu.com'
chrome_pub_key_url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
chrome_export_key_id: 'D38B4796'

veracrypt_download_url: 'https://github.com/veracrypt/VeraCrypt/releases/download/VeraCrypt_1.26.14/veracrypt-1.26.14-Ubuntu-20.04-amd64.deb'

discord_download_url: 'https://discord.com/api/download?platform=linux&format=deb'

signal_key_url: 'https://updates.signal.org/desktop/apt/keys.asc'
signal_gpg_dest: '/usr/share/keyrings/signal-desktop-keyring.gpg'
signal_repo_url: 'deb [arch=amd64 signed-by={{ signal_gpg_dest }}] https://updates.signal.org/desktop/apt xenial main'

cameractrls_dependencies:
  - libsdl2-2.0-0
  - libturbojpeg

cameractrls_git_repo: https://github.com/soyersoyer/cameractrls.git

regolith_key_url: 'https://regolith-desktop.org/regolith.key'
regolith_gpg_dest: '/usr/share/keyrings/regolith-archive-keyring.gpg'
regolith_repo_url: 'deb [arch=amd64 signed-by={{ regolith_gpg_dest }}] https://regolith-desktop.org/release-3_0-ubuntu-jammy-amd64 jammy main'
regolith_packages:
  - regolith-desktop
  - regolith-look-nord
  - regolith-session-flashback
  - regolith-system-ubuntu
i3_packages:
  - i3xrocks-battery
  - i3xrocks-bluetooth
  - i3xrocks-cpu-usage
  - i3xrocks-disk-capacity
  - i3xrocks-focused-window-name
  - i3xrocks-info
  - i3xrocks-memory
  - i3xrocks-microphone
  - i3xrocks-net-traffic
  - i3xrocks-rofication
  - i3xrocks-temp
  - i3xrocks-time
  - i3xrocks-updates
  - i3xrocks-volume
  - i3xrocks-wifi
  # - i3xrocks-app-launcher
  # - i3xrocks-key-indicator
  # - i3xrocks-keyboard-layout
  # - i3xrocks-media-player
  # - i3xrocks-next-workspace
  # - i3xrocks-nm-vpn
  # - i3xrocks-openvpn
  # - i3xrocks-tailscale
  # - i3xrocks-weather

i3_config_block: |
    bindsym $mod+p exec flameshot gui
    bindsym $mod+Ctrl+p exec flameshot full -p /tmp/
    bindsym $mod+s exec gnome-control-center sound
    bindsym $mod+Shift+w exec /usr/bin/python3 /opt/cameractrls/cameractrlsgtk4.py
    bindsym $mod+m exec pactl set-source-mute @DEFAULT_SOURCE@ toggle && notify-send --icon=/dev/null --expire-time=500 "$(pactl get-source-mute @DEFAULT_SOURCE@)"

i3_xresources_block: |
    gtk.font_name: Nerd Font Mono 10
    regolith.wallpaper.file: /opt/lalubuntu/screens/wallpaper.png
    regolith.wallpaper.options: stretched
