---
# defaults file for gui-tools
gui_tools_to_install:
  - apt-transport-https
  - arandr
  - bless
  - cheese
  - filezilla
  - flameshot
  - gparted
  - kompare
  - libreoffice
  - mplayer
  - obs-studio
  - qbittorrent
  - qemu
  - torbrowser-launcher
  - usb-creator-gtk
  - vlc
  - wireshark
  - libgtk-3-dev

chrome_gpg_dest: '/etc/apt/trusted.gpg.d/chrome.gpg'
chrome_deb_url: 'deb [arch=amd64 signed-by={{ chrome_gpg_dest }}] https://dl.google.com/linux/chrome/deb/ stable main'
chrome_gpg_key_id: '78BD65473CB3BD13'
chrome_key_server: 'keyserver.ubuntu.com'
chrome_pub_key_url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
chrome_export_key_id: 'D38B4796'

veracrypt_download_url: 'https://api.github.com/repos/veracrypt/veracrypt/releases/latest'

nomachine_download_url: 'https://downloads.nomachine.com/download/?id=5'

discord_download_url: 'https://discord.com/api/download?platform=linux&format=deb'

vscode_deb_url: 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64'

signal_key_url: 'https://updates.signal.org/desktop/apt/keys.asc'
signal_gpg_dest: '/usr/share/keyrings/signal-desktop-keyring.gpg'
signal_repo_url: 'deb [arch=amd64 signed-by={{ signal_gpg_dest }}] https://updates.signal.org/desktop/apt xenial main'

regolith_key_url: 'https://regolith-desktop.org/regolith.key'
regolith_gpg_dest: '/usr/share/keyrings/regolith-archive-keyring.gpg'
regolith_repo_url: 'deb [arch=amd64 signed-by={{ regolith_gpg_dest }}] https://regolith-desktop.org/release-3_0-ubuntu-jammy-amd64 jammy main'
regolith_packages:
  - regolith-desktop
  - regolith-look-nord
  - regolith-session-flashback
  - regolith-system-ubuntu
i3_packages:
  - i3xrocks-battery
  - i3xrocks-bluetooth
  - i3xrocks-cpu-usage
  - i3xrocks-disk-capacity
  - i3xrocks-focused-window-name
  - i3xrocks-info
  - i3xrocks-memory
  - i3xrocks-microphone
  - i3xrocks-net-traffic
  - i3xrocks-rofication
  - i3xrocks-temp
  - i3xrocks-time
  - i3xrocks-updates
  - i3xrocks-volume
  - i3xrocks-wifi
  # - i3xrocks-app-launcher
  # - i3xrocks-key-indicator
  # - i3xrocks-keyboard-layout
  # - i3xrocks-media-player
  # - i3xrocks-next-workspace
  # - i3xrocks-nm-vpn
  # - i3xrocks-openvpn
  # - i3xrocks-tailscale
  # - i3xrocks-weather

i3_config_block: |
    bindsym $mod+p exec flameshot gui
    bindsym $mod+Ctrl+p exec flameshot full -p /tmp/
    bindsym $mod+m exec xrandr --output $(xrandr | grep ' connected ' -m 1 | awk '{ print $1 }') --off
    bindsym $mod+Shift+m exec xrandr --output $(xrandr | grep ' connected ' -m 1 | awk '{ print $1 }') --auto

wallpaper_dl_url: https://i.postimg.cc/YSX66PDS/wallpaper.jpg

i3_xresources_block: |
    gtk.font_name: Nerd Font Mono 10
    regolith.wallpaper.file: /usr/share/backgrounds/cust_wallpaper.jpg
