---
- name: Update apt repo/cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true

- name: Upgrade all packages
  apt: upgrade=yes force_apt_get=yes
  become: true

- name: Installing Packages
  package:
    name:
          - apt-transport-https
          - autoconf
          - bat
          - binwalk
          - bison
          - build-essential
          - ca-certificates
          - cloc
          - cmake
          - cmake-curses-gui
          - curl
          - dos2unix
          - expect
          - ffmpeg
          - foremost
          - fswebcam
          - gcc
          - gdb
          - git
          - gnupg
          - hashid
          - hexyl
          - hwinfo
          - imagemagick
          - inotify-tools
          - jq
          - libbz2-dev
          - libcurl4-openssl-dev
          - libffi-dev
          - libgd-dev
          - libimage-exiftool-perl
          - libleptonica-dev
          - liblzma-dev
          - libncursesw5-dev
          - libonig-dev
          - libpcap-dev
          - libpq-dev
          - libreadline-dev
          - libsqlite3-dev
          - libssl-dev
          - libtesseract-dev
          - libxml2-dev
          - libxml2-utils
          - libxmlsec1-dev
          - libyaml-dev
          - libzip-dev
          - linux-tools-common
          - linux-tools-generic
          - llvm
          - locate
          - lsb-release
          - lsof
          - ltrace
          - make
          - net-tools
          - ngrep
          - nmap
          - parallel
          - python3-dev
          - python3-pip
          - python3-venv
          - re2c
          - ripgrep
          - rlwrap
          - socat
          - sshpass
          - tk-dev
          - tmux
          - tor
          - trash-cli
          - tree
          - unzip
          - vbindiff
          - vim
          - wget
          - wl-clipboard
          - xclip
          - xz-utils
          - zip
          - zlib1g-dev
          - software-properties-common
    state: latest
  become: true
