---
- name: Install cargo-based tools (this will take lot of time to install)
  ansible.builtin.shell: mise exec -- cargo install {{ item }}
  with_items:
    - bottom
    - du-dust
    - exa
    - git-delta
    - htmlq
    - spacer
    - viu
    - xsv
    - --git https://github.com/asciinema/asciinema