- name: Install docker only if /usr/bin/docker does not exist
  ansible.builtin.stat:
    path: '/usr/bin/docker'
  register: docker_installed

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url : 'https://download.docker.com/linux/ubuntu/gpg'
    dest: '/tmp/docker_gpg'
  when: not docker_installed.stat.exists

- name: De-Armor Docker GPG key
  ansible.builtin.shell: 'gpg --dearmor < /tmp/docker_gpg > /usr/share/keyrings/docker-archive-keyring.gpg && rm /tmp/docker_gpg'
  become: true
  when: not docker_installed.stat.exists

- name: Add Docker repository
  ansible.builtin.lineinfile:
    path: '/etc/apt/sources.list.d/docker.list'
    line: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable'
    create: yes
  become: true
  when: not docker_installed.stat.exists

- name: Install Dockers components
  ansible.builtin.package:
    update_cache: yes
    name: '{{ item }}'
    state: latest
  become: true
  when: not docker_installed.stat.exists
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin