- name: Install docker only if /usr/bin/docker does not exist
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: docker_installed

- name: Add Docker key
  ansible.builtin.shell: "curl -fsSL {{ docker_key_url }} | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
  become: true
  when: not docker_installed.stat.exists

- name: Add Docker repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: '{{ docker_deb_url }}'
    create: yes
  become: true
  when: not docker_installed.stat.exists

- name: Install Dockers components
  ansible.builtin.package:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  loop: "{{ docker_components }}"
  become: true
  when: not docker_installed.stat.exists