---
- name: Install mise only if {{ ansible_env.HOME }}/.local/bin/mise does not exist
  ansible.builtin.stat:
    path: '{{ ansible_env.HOME }}/.local/bin/mise'
  register: mise_installed

- name: Create directory /etc/apt/keyrings
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: directory
    mode: '0755'
  when: not mise_installed.stat.exists

- name: Download installation script from https://mise.jdx.dev
  ansible.builtin.get_url:
    url: https://mise.jdx.dev/install.sh
    dest: /tmp/install.sh
    mode: '0755'

- name: Execute the installation script
  ansible.builtin.shell: /tmp/install.sh

- name: Remove old rtx config from shell configuration files
  ansible.builtin.lineinfile:
    path: '{{ ansible_env.HOME }}/.{{ item }}rc'
    state: absent
    regexp: 'eval .*rtx activate {{ item }}'
    backrefs: yes
  loop:
    - bash
    - zsh

- name: Add mise activation to shell configuration files
  ansible.builtin.lineinfile:
    path: '{{ ansible_env.HOME }}/.{{ item }}rc'
    state: present
    line: 'eval "$(~/.local/bin/mise activate {{ item }})"'
    insertafter: EOF
  loop:
    - bash
    - zsh

- name: Set mise settings to build python
  ansible.builtin.shell: zsh -c 'mise settings set python_compile 1'

- name: Install and mise-based tools (this will take lot of time to install)
  ansible.builtin.shell: zsh -c 'mise install {{ item }}@latest -y && mise use -g {{ item }}@latest'
  with_items: '{{ mise_tools }}'

- name: Install grumpy php that yells stuff yet works
  ansible.builtin.shell: zsh -c 'mise install php@latest -y && mise use -g php@latest || true'

- name: Install lazyvim only if ~/.config/nvim does not exist
  ansible.builtin.stat:
    path: '{{ ansible_env.HOME }}/.config/nvim'
  register: lazyvim_installed

- name: Clone LazyVim from Git
  ansible.builtin.git:
    repo: https://github.com/LazyVim/starter
    dest: '{{ ansible_env.HOME }}/.config/nvim'
    update: yes
    force: yes
  when: lazyvim_installed.stat.exists == False

- name: Disable mouse integration in Neovim
  ansible.builtin.lineinfile:
    path: '{{ ansible_env.HOME }}/.config/nvim/init.lua'
    state: present
    line: 'vim.opt.mouse = ""'
    insertafter: EOF
