- name: Install pipx packages
  ansible.builtin.shell: pipx install {{ item }} && pipx inject {{ item }} setuptools
  with_items:
    - argcomplete
    - bypass-url-parser
    - dirsearch
    - exegol
    - pre-commit
    - sqlmap
    - trash-cli
    - wafw00f
    - yt-dlp
    - semgrep

- name: Add exegol autocompletion to shell configuration files
  ansible.builtin.lineinfile:
    path: '{{ ansible_env.HOME }}/.{{ item }}rc'
    state: present
    line: 'eval "$(register-python-argcomplete --no-defaults exegol)"'
    insertafter: EOF
  loop:
    - bash
    - zsh
