---
- name: Install rtx only if /usr/bin/rtx does not exist
  ansible.builtin.stat:
    path: /usr/bin/rtx
  register: rtx_installed

- name: Create directory /etc/apt/keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: not rtx_installed.stat.exists

- name: Add RTX key
  ansible.builtin.shell: "wget -qO - {{ rtx_pub_url }} | gpg --dearmor > /etc/apt/keyrings/rtx-archive-keyring.gpg"
  become: true
  when: not rtx_installed.stat.exists

- name: Add RTX repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/rtx.list
    line: '{{ rtx_deb_url }}'
    create: yes
  become: true
  when: not rtx_installed.stat.exists

- name: Install RTX
  ansible.builtin.package:
    update_cache: yes
    name:
      - rtx
    state: latest
  become: true
  when: not rtx_installed.stat.exists

- name: Add RTX activation to shell configuration files
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.{{ item }}rc"
    line: 'eval "$(/usr/bin/rtx activate {{ item }})"'
    create: yes
  loop:
    - bash
    - zsh

- name: Install and rtx-based tools (this will take lot of time to install)
  ansible.builtin.shell: zsh -c 'source {{ ansible_env.HOME }}/.zshrc && rtx install {{ item }}@latest -y && rtx global {{ item }}@latest'
  with_items: '{{ rtx_tools }}'
  when: not rtx_installed.stat.exists
