---
- name: Create a Storage Dir (if it doesn't exist)
  ansible.builtin.file:
    path: '/DATA'
    state: directory
    mode: '0755'
  become: true

- name: Set Storage Dir Ownership to {{ ansible_user_id }}
  ansible.builtin.file:
    path: '/DATA'
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
    recurse: yes
  become: true

- name: Create {{ ansible_env.HOME }}/.ssh directory (if it doesn't exist)
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.ssh'
    state: directory
    mode: '0755'

