- name: Set the default editor alternative to vim
  ansible.builtin.alternatives:
    name: editor
    path: '/usr/bin/vim.basic'
  become: true

- name: Set the default editor alternative to vim for the current user
  ansible.builtin.alternatives:
    name: editor
    path: '/usr/bin/vim.basic'

- name: /etc/vim/vimrc.local configuration
  ansible.builtin.blockinfile:
    path: '/etc/vim/vimrc.local'
    block: '{{ vimrc_content }}'
    marker: '"'
    mode: '0644'
    create: yes
  become: true
