- name: Enable zsh plugins
  ansible.builtin.shell: "zsh -c 'source ~/.zshrc && omz plugin enable {{ item }} || true'"
  with_items: '{{ omz_plugins_to_enable }}'

- name: Disable zsh plugins
  ansible.builtin.shell: "zsh -c 'source ~/.zshrc && omz plugin disable {{ item }} || true'"
  with_items: '{{ zsh_plugins_to_disable }}'

- name: Fix wildcard in history
  ansible.builtin.shell: "zsh -c 'source ~/.zshrc && set mark-modified-lines off'"
