- name: Change the default shell to zsh
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    shell: /bin/zsh
  become: true

- name: Clone Oh My Zsh repository
  ansible.builtin.git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh'
    force: yes
    update: yes
  become_user: '{{ ansible_user_id }}'

- name: Check if ~/.zshrc exists
  ansible.builtin.stat:
    path: '{{ ansible_env.HOME }}/.zshrc'
  register: zshrc_stat

- name: Copy zshrc.zsh-template to ~/.zshrc if not existing
  ansible.builtin.copy:
    src: '{{ ansible_env.HOME }}/.oh-my-zsh/templates/zshrc.zsh-template'
    dest: '{{ ansible_env.HOME }}/.zshrc'
  when: not zshrc_stat.stat.exists

- name: Set the zsh theme to af-magic
  ansible.builtin.replace:
    path: '{{ ansible_env.HOME }}/.zshrc'
    regexp: '^ZSH_THEME=.*$'
    replace: 'ZSH_THEME="af-magic"'

- name: Adding configs lines to zsh
  ansible.builtin.lineinfile:
    path: '{{ ansible_env.HOME }}/.zshrc'
    insertbefore: 'source.*oh-my-zsh.sh'
    line: '{{ item }}'
    state: present
  with_items:
  - DISABLE_MAGIC_FUNCTIONS=true

- name: Clone zsh plugins as git repositories
  ansible.builtin.git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
  loop:
    - { repo: 'https://github.com/zsh-users/zsh-completions', dest: '{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-completions' }
    - { repo: 'https://github.com/zsh-users/zsh-autosuggestions', dest: '{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-autosuggestions' }
    - { repo: 'https://github.com/zsh-users/zsh-syntax-highlighting', dest: '{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-syntax-highlighting' }
  when: not item.dest is exists

- name: Clone fzf repository
  ansible.builtin.git:
    repo: 'https://github.com/junegunn/fzf'
    dest: '{{ ansible_env.HOME }}/.fzf'
    depth: 1

- name: Run fzf installation script
  ansible.builtin.shell: "zsh -c '~/.fzf/install --all'"

- name: Add line to shell configuration files
  ansible.builtin.lineinfile:
    path: '{{ item }}'
    line: 'source /opt/lalubuntu/aliases'
    insertafter: EOF
  with_items:
    - ~/.zshrc
    - ~/.bashrc

- name: Tmux configuration
  ansible.builtin.blockinfile:
    path: '{{ ansible_env.HOME }}/.tmux.conf'
    block: |
      set-option -g mouse off
      set-option -g history-limit 5000
      set-option -g status-bg colour231
    create: yes