---
- name: Check if BurpSuite is already installed
  ansible.builtin.stat:
    path: '/opt/BurpSuiteCommunity'
  register: burpsuite_installed

- name: Download BurpSuite
  ansible.builtin.get_url:
    url: 'https://portswigger-cdn.net/burp/releases/download?product=community&version=2024.8.4&type=Linux'
    dest: '/tmp/burp-installer.sh'
  when: not burpsuite_installed.stat.exists

- name: Install BurpSuite
  ansible.builtin.shell: "bash /tmp/burp-installer.sh -q"
  when: not burpsuite_installed.stat.exists

- name: Delete BurpSuite install files
  ansible.builtin.file:
    path: '/tmp/burp-installer.sh'
    state: absent
  when: not burpsuite_installed.stat.exists

- name: Move Burp Install to /opt
  become: true
  ansible.builtin.shell: |
    set -x
    mv '{{ ansible_env.HOME }}/BurpSuiteCommunity' /opt/
    sed -i 's#{{ ansible_env.HOME }}#/opt#g' '{{ ansible_env.HOME }}/.gnome/apps/install'*BurpSuiteCommunity.desktop
