---
- name: Check if BurpSuite is already installed
  ansible.builtin.stat:
    path: '/opt/lbtools/BurpSuiteCommunity'
  register: burpsuite_installed

- name: Download BurpSuite
  ansible.builtin.get_url:
    url: 'https://portswigger-cdn.net/burp/releases/download?product=community&version=2024.8.4&type=Linux'
    dest: '/tmp/burp-installer.sh'
  when: not burpsuite_installed.stat.exists

- name: Install BurpSuite
  ansible.builtin.shell: "bash /tmp/burp-installer.sh -q"
  when: not burpsuite_installed.stat.exists

- name: Delete BurpSuite install files
  ansible.builtin.file:
    path: '/tmp/burp-installer.sh'
    state: absent
  when: not burpsuite_installed.stat.exists


- name: Move Burp Install to /opt/lbtools
  command: zsh -c 'exa -Tll -L 2 .'
  when: not burpsuite_installed.stat.exists

- name: Move Burp Install to /opt/lbtools
  command: mv "{{ ansible_env.HOME }}/BurpSuiteCommunity" /opt/lbtools/BurpSuiteCommunity
  when: not burpsuite_installed.stat.exists

- name: Find all matching BurpSuiteCommunity desktop files in .local/share/applications
  ansible.builtin.find:
    paths: '{{ ansible_env.HOME }}/.local/share/applications/'
    patterns: 'install4j_*BurpSuiteCommunity.desktop'
  register: burpsuite_local_files

- name: Find all matching BurpSuiteCommunity desktop files in .gnome/apps
  ansible.builtin.find:
    paths: '{{ ansible_env.HOME }}/.gnome/apps/'
    patterns: 'install4j*BurpSuiteCommunity.desktop'
  register: burpsuite_gnome_files

- name: Combine results from both searches
  set_fact:
    burpsuite_files: "{{ burpsuite_local_files.files + burpsuite_gnome_files.files }}"

- name: Tweak burp desktop files
  ansible.builtin.replace:
    path: '{{ item.path }}'
    regexp: '{{ ansible_env.HOME }}'
    replace: '/opt/lbtools'
  loop: '{{ burpsuite_files }}'
  when: burpsuite_files | length > 0

- name: Allow katana / burp / obs headless browsers to work
  ansible.builtin.lineinfile:
    path: '/etc/sysctl.conf'
    line: 'kernel.apparmor_restrict_unprivileged_userns=0'
    insertafter: EOF
  become: true

- name: Apply new sysctl config
  ansible.builtin.shell: "sysctl -p"
  become: true
