---
- name: Install various Go packages
  ansible.builtin.shell: "mise exec -- go install '{{ item }}@latest'"
  loop: '{{ go_packages }}'

- name: Run pdtm and install all tools
  ansible.builtin.shell: "zsh -c 'mise exec -- pdtm -install-all'"

- name: Run pdtm path config
  ansible.builtin.shell: "zsh -c 'mise exec -- pdtm -install-path'"
