---
- name: Install various Go packages
  ansible.builtin.shell: "mise exec -- go install '{{ item }}@latest'"
  with_items:
    - github.com/antonmedv/fx
    - github.com/ffuf/ffuf
    - github.com/glitchedgitz/cook/v2/cmd/cook
    - github.com/jesseduffield/lazygit
    - github.com/lc/gau/v2/cmd/gau
    - github.com/projectdiscovery/pdtm/cmd/pdtm
    - github.com/sw33tLie/sns
    - github.com/wader/fq
    - github.com/x90skysn3k/brutespray
    - github.com/xm1k3/cent
    - github.com/tomnomnom/waybackurls

- name: Run pdtm and install all tools
  ansible.builtin.shell: "zsh -c 'mise exec -- pdtm -install-all'"

- name: Run pdtm path config
  ansible.builtin.shell: "zsh -c 'mise exec -- pdtm -install-path'"
