---
- name: Try to solve github username weird new issue
  ansible.builtin.shell: git config --global user.name hacker
  become: true

- name: Try to solve github username weird new issue
  ansible.builtin.shell: git config --global user.name hacker

- name: Create lbtools directory
  become: true
  ansible.builtin.file:
    path: '/opt/lbtools'
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
    state: directory
    mode: '0755'
  
- name: Clone tools from Git
  ansible.builtin.git:
    repo: '{{ item.repo }}'
    dest: '/opt/lbtools/{{ item.dest }}'
    update: yes
  with_items:
    - repo: https://github.com/jpillora/chisel
      dest: chisel
    - repo: https://github.com/ambionics/phpggc
      dest: phpggc
    - repo: https://github.com/CBHue/PyFuscation
      dest: PyFuscation
    - repo: https://github.com/christophetd/CloudFlair
      dest: CloudFlair
    - repo: https://github.com/minos-org/minos-static
      dest: minos-static
    - repo: https://github.com/offensive-security/exploit-database
      dest: exploit-database
    - repo: https://gitlab.com/exploit-database/exploitdb
      dest: exploitdb
    - repo: https://github.com/laluka/pty4all
      dest: pty4all
    - repo: https://github.com/laluka/pypotomux
      dest: pypotomux

- name: Create a lists directory
  ansible.builtin.file:
    path: /opt/lists
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
    recurse: 'yes'
  become: true

- name: Set Git core.autocrlf to false globally, otherwise a few wordlists repos break
  ansible.builtin.shell: git config --global core.autocrlf false

- name: Clone wordlists from Git
  ansible.builtin.git:
    repo: '{{ item.repo }}'
    dest: '/opt/lists/{{ item.dest }}'
    update: yes
    force: yes
  with_items:
    - repo: https://github.com/swisskyrepo/PayloadsAllTheThings
      dest: PayloadsAllTheThings
    - repo: https://github.com/projectdiscovery/fuzzing-templates
      dest: fuzzing-templates
    - repo: https://github.com/1N3/BruteX
      dest: BruteX
    - repo: https://github.com/1N3/IntruderPayloads
      dest: IntruderPayloads
    - repo: https://github.com/berzerk0/Probable-Wordlists
      dest: Probable-Wordlists
    - repo: https://github.com/cujanovic/Open-Redirect-Payloads
      dest: Open-Redirect-Payloads
    - repo: https://github.com/danielmiessler/SecLists
      dest: SecLists
    - repo: https://github.com/ignis-sec/Pwdb-Public
      dest: Pwdb-Public
    - repo: https://github.com/Karanxa/Bug-Bounty-Wordlists
      dest: Bug-Bounty-Wordlists
    - repo: https://github.com/tarraschk/richelieu
      dest: richelieu
  # Too heavy: 9.5G is a no go for docker images :(
  # - repo: https://github.com/p0dalirius/webapp-wordlists
  #   dest: webapp-wordlists

- name: Download rockyou wordlist
  ansible.builtin.get_url:
    url: 'https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt'
    dest: '/opt/lists/rockyou.txt'