---
- name: Clone tools from Git
  ansible.builtin.git:
    repo: '{{ item.repo }}'
    dest: '/opt/{{ item.dest }}'
    update: yes
  loop: '{{ git_repositories }}'
  become: true

- name: Change ownership of the directory
  ansible.builtin.file:
    path: '/opt/{{ item.dest }}'
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
    recurse: yes
  loop: '{{ git_repositories }}'
  become: true

- name: Create a lists directory
  ansible.builtin.file:
    path: /opt/lists
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
    recurse: 'yes'
  become: true

- name: Set Git core.autocrlf to false globally, otherwise a few wordlists repos break
  ansible.builtin.shell: git config --global core.autocrlf false

- name: Clone wordlists from Git
  ansible.builtin.git:
    repo: '{{ item.repo }}'
    dest: '/opt/lists/{{ item.dest }}'
    update: yes
    force: yes
  loop: '{{ git_wordlists }}'
