name: packer

on:
  push:

env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: DEBUG
        id: debug
        run: "find . ; echo $SHELL ; which packer"

      - name: Run `packer init`
        id: init
        run: "cd packer && packer init ./lbt-docker.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "cd packer && packer validate ./lbt-docker.pkr.hcl"

      - name: Run `packer build docker pre-install`
        id: pre_install
        run: |
          cd packer
          export PACKER_LOG=1
          export PACKER_LOG_PATH=/dev/stdout
          docker images -a
          packer build -only=lbt-pre-install.docker.lbt lbt-docker.pkr.hcl
          docker images -a

      - name: Run `packer build docker base-install`
        id: base_install
        run: |
          cd packer
          export PACKER_LOG=1
          export PACKER_LOG_PATH=/dev/stdout
          docker images -a 
          packer build -only=lbt-base-install.docker.lbt lbt-docker.pkr.hcl
          docker images -a 

# packer build -only=lbt-offensive-stuff.docker.lbt lbt-docker.pkr.hcl
# packer build -only=lbt-gui-tools.docker.lbt lbt-docker.pkr.hcl
