name: packer

on:
  push:

env:
  PRODUCT_VERSION: "1.8.6" # or: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: DEBUG
        id: debug
        run: "find . ; echo $SHELL ; which packer"

      - name: Run `packer init`
        id: init
        run: "cd packer && packer init ./lbt-docker.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "cd packer && packer validate ./lbt-docker.pkr.hcl"

      - name: Run `packer build`
        id: build
        run: "cd packer && PACKER_LOG=1 PACKER_LOG_PATH=/dev/stdout packer build -parallel-builds=1 ./lbt-docker.pkr.hcl"
