name: packer

on:
  push:
  schedule:
    - cron:  '30 7 * * *'

env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    environment: docker-login-push
    env:
      PACKER_LOG: 1
      PACKER_LOG_PATH: /dev/stdout
      DOCK_USER: ${{ secrets.DOCK_USER }}
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Romve useless stuff for docker size
        id: size_cleanup
        run: |
          df -h
          sudo docker system prune -a -f --volumes
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          df -h

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        env:
          PACKER_LOG: "0"
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        env:
          PACKER_LOG: "0"
        run: |
          packer init ./packer/lbt-docker.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: |
          packer validate ./packer/lbt-docker.pkr.hcl

      - name: Run `packer build docker pre-install`
        id: pre_install
        run: |
          df -h
          packer build -only=lbt-pre-install.docker.lbt ./packer/lbt-docker.pkr.hcl

      # - name: Run `packer build docker base-install`
      #   id: base_install
      #   run: |
      #     df -h
      #     packer build -only=lbt-base-install.docker.lbt ./packer/lbt-docker.pkr.hcl

      # - name: Run `packer build docker lbt-offensive-stuff`
      #   id: lbt_offensive_stuff
      #   run: |
      #     df -h
      #     packer build -only=lbt-offensive-stuff.docker.lbt ./packer/lbt-docker.pkr.hcl

      # - name: Run `packer build docker lbt-gui-tools`
      #   id: lbt_gui_tools
      #   run: |
      #     df -h
      #     packer build -only=lbt-gui-tools.docker.lbt ./packer/lbt-docker.pkr.hcl
