name: packer

on:
  push:

env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Maximize build space # https://github.com/marketplace/actions/maximize-build-disk-space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: DEBUG
        id: debug
        run: |
          find .
          echo $SHELL
          uname -a
          df -h
          docker system prune -a -f --volumes
          df -h

      - name: Run `packer init`
        id: init
        run: "cd packer && packer init ./lbt-docker.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "cd packer && packer validate ./lbt-docker.pkr.hcl"

      - name: Run `packer build docker pre-install`
        id: pre_install
        run: |
          cd packer
          df -h
          export PACKER_LOG=1
          export PACKER_LOG_PATH=/dev/stdout
          packer build -only=lbt-pre-install.docker.lbt lbt-docker.pkr.hcl

      - name: Run `packer build docker base-install`
        id: base_install
        run: |
          cd packer
          df -h
          export PACKER_LOG=1
          export PACKER_LOG_PATH=/dev/stdout
          packer build -only=lbt-base-install.docker.lbt lbt-docker.pkr.hcl

      - name: Run `packer build docker lbt-offensive-stuff`
        id: lbt_offensive_stuff
        run: |
          cd packer
          df -h
          export PACKER_LOG=1
          export PACKER_LOG_PATH=/dev/stdout
          packer build -only=lbt-offensive-stuff.docker.lbt lbt-docker.pkr.hcl

      # - name: Run `packer build docker lbt-gui-tools`
      #   id: lbt_gui_tools
      #   run: |
      #     cd packer
      #     df -h
      #     export PACKER_LOG=1
      #     export PACKER_LOG_PATH=/dev/stdout
      #     packer build -only=lbt-gui-tools.docker.lbt lbt-docker.pkr.hcl
