name: packer

on:
  push:

env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Daily Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run:
          shell: bash
          working-directory: ${{ github.workspace }}/packer
          command: packer init lbt-docker.pkr.hcl

      - name: Run `packer validate`
        id: validate
        run:
          shell: bash
          working-directory: ${{ github.workspace }}/packer
          command: PACKER_LOG=1 PACKER_LOG_PATH=/dev/stdout packer build -only="lbt-pre-install.docker.lbt" lbt-docker.pkr.hcl