name: packer

on:
  push:

env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: DEBUG
        id: debug
        run: "find . ; echo $SHELL ; which packer"

      - name: Run `packer init`
        id: init
        run: "cd packer && packer init ./lbt-docker.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "cd packer && packer validate ./lbt-docker.pkr.hcl"

      - name: Run `packer build lbt-pre-install.docker.lbt`
        id: lbt_pre_install_docker
        run: "cd packer && PACKER_LOG=1 PACKER_LOG_PATH=/dev/stdout packer build -only=lbt-pre-install.docker.lbt lbt-docker.pkr.hcl"

      - name: Run `packer build lbt-base-install.docker.lbt`
        id: lbt_base_install_docker
        run: "cd packer && PACKER_LOG=1 PACKER_LOG_PATH=/dev/stdout packer build -only=lbt-base-install.docker.lbt lbt-docker.pkr.hcl"

      - name: Run `packer build lbt-offensive-stuff.docker.lbt`
        id: lbt_offensive_stuff_docker
        run: "cd packer && PACKER_LOG=1 PACKER_LOG_PATH=/dev/stdout packer build -only=lbt-offensive-stuff.docker.lbt lbt-docker.pkr.hcl"

      - name: Run `packer build lbt-gui-tools.docker.lbt`
        id: lbt_gui_tools_docker
        run: "cd packer && PACKER_LOG=1 PACKER_LOG_PATH=/dev/stdout packer build -only=lbt-gui-tools.docker.lbt lbt-docker.pkr.hcl"
